### ISSUE TITLE
Can we use a jsx syntax like in React (some dsl for this one)?

### ISSUE THREAD

**Issue by xgrommx** [fable-compiler/fable-arch#15]

**Comment by MangelMaxime** [comment]
For the moment no because Fable is compiling in Javascript.

Somehow, we consider F# syntax as the DSL.

**Comment by xgrommx** [comment]
@MangelMaxime I mean smth like https://github.com/pzavolinsky/elmx

**Comment by mastoj** [comment]
@xgrommx it want be part of the core part. If someone wants to add a precompiler that handles that type of dsl I wouldn't stop them. I think using F# as dsl will give you greater benefit than using another dsl that you precompiles to F#, which you then compile down to js.

Personally I do like it as straight F# since it is easier to test, fewer abstractions, and F# is quite concise.

Closing this since it want be part of this project.
